# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LANDSControl.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_landsControl(object):
    def setupUi(self, landsControl):
        landsControl.setObjectName("landsControl")
        landsControl.resize(780, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(landsControl.sizePolicy().hasHeightForWidth())
        landsControl.setSizePolicy(sizePolicy)
        landsControl.setMinimumSize(QtCore.QSize(780, 450))
        landsControl.setMaximumSize(QtCore.QSize(780, 450))
        self.centralwidget = QtWidgets.QWidget(landsControl)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 761, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(120, 10, 281, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(540, 10, 101, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 10, 101, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 741, 291))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 381, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 131, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 30, 151, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 151, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox.setGeometry(QtCore.QRect(200, 70, 101, 30))
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMaximum(300.0)
        self.doubleSpinBox.setProperty("value", 200.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(200, 110, 101, 30))
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(300.0)
        self.doubleSpinBox_2.setProperty("value", 72.5)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 151, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 30, 321, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(190, 29, 101, 30))
        self.doubleSpinBox_4.setDecimals(0)
        self.doubleSpinBox_4.setMaximum(2000.0)
        self.doubleSpinBox_4.setProperty("value", 1500.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(190, 70, 101, 30))
        self.doubleSpinBox_3.setDecimals(2)
        self.doubleSpinBox_3.setMaximum(300.0)
        self.doubleSpinBox_3.setProperty("value", 22.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(190, 110, 101, 30))
        self.doubleSpinBox_5.setDecimals(2)
        self.doubleSpinBox_5.setMaximum(300.0)
        self.doubleSpinBox_5.setProperty("value", 40.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(190, 150, 101, 30))
        self.doubleSpinBox_6.setDecimals(2)
        self.doubleSpinBox_6.setMaximum(300.0)
        self.doubleSpinBox_6.setProperty("value", 4.25)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 190, 221, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber.setGeometry(QtCore.QRect(140, 60, 64, 23))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_2.setGeometry(QtCore.QRect(140, 30, 64, 23))
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 3500.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 220, 321, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(190, 19, 101, 30))
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setMaximum(2000.0)
        self.doubleSpinBox_7.setProperty("value", 60.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 200, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 10, 101, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        landsControl.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(landsControl)
        self.statusbar.setObjectName("statusbar")
        landsControl.setStatusBar(self.statusbar)

        self.retranslateUi(landsControl)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(landsControl)

    def retranslateUi(self, landsControl):
        _translate = QtCore.QCoreApplication.translate
        landsControl.setWindowTitle(_translate("landsControl", "LANDS Control"))
        self.comboBox.setItemText(0, _translate("landsControl", "SWCNTs in IPA"))
        self.pushButton.setText(_translate("landsControl", "New Recipe"))
        self.pushButton_2.setText(_translate("landsControl", "Delete Recipe"))
        self.label.setText(_translate("landsControl", "Select Recipe:"))
        self.groupBox.setTitle(_translate("landsControl", "SWCNTs in IPA"))
        self.groupBox_3.setTitle(_translate("landsControl", "Motion Control"))
        self.label_2.setText(_translate("landsControl", "X-Y Motion:"))
        self.comboBox_2.setItemText(0, _translate("landsControl", "Sawtooth Pattern"))
        self.label_3.setText(_translate("landsControl", "Speed [mm/s]:"))
        self.label_10.setText(_translate("landsControl", "Nozzle Height [mm]:"))
        self.groupBox_2.setTitle(_translate("landsControl", "Syringe Pump Settings"))
        self.label_6.setText(_translate("landsControl", "Maximum Force [N]:"))
        self.label_5.setText(_translate("landsControl", "Syringe Diameter [mm]:"))
        self.label_7.setText(_translate("landsControl", "Infusion Volume [mL]:"))
        self.label_8.setText(_translate("landsControl", "Infusion Rate [mL/min]:"))
        self.groupBox_4.setTitle(_translate("landsControl", "Gas Pressures"))
        self.label_4.setText(_translate("landsControl", "Fan [mBar]:"))
        self.label_9.setText(_translate("landsControl", "Atomizing [mBar]:"))
        self.groupBox_5.setTitle(_translate("landsControl", "Bed Heater"))
        self.label_11.setText(_translate("landsControl", "Bed Temperature [°C]"))
        self.pushButton_7.setText(_translate("landsControl", "Run"))
        self.pushButton_6.setText(_translate("landsControl", "Save Recipe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("landsControl", "Recipes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("landsControl", "Direct Machine Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("landsControl", "X-Y Motion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("landsControl", "Miscellaneous"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("landsControl", "I\'m Feeling Lucky"))

